all:
	python3 freq_analysis.py > frequency_backdoor.txt < backdoor
	python3 freq_analysis.py > frequency_trojan.txt < trojan
	python3 freq_analysis.py > frequency_benign.txt < benign
	python3 freq_analysis.py > frequency_trojan_downloader.txt < trojan_downloader
	python3 freq_analysis.py > frequency_trojan_dropper.txt < trojan_dropper
	python3 freq_analysis.py > frequency_virus.txt < virus
	python3 freq_analysis.py > frequency_worm.txt < worm
